### ISSUE TITLE
Unable to Send URLs containing Ampersands

### ISSUE THREAD

**Issue by neutronium-alchemist** [mozz100/screenserve#6]
When sending URLs via the API, content after ampersands(&) is truncated, making some URLs unreachable. 

This works fine via the webpage, however.

e.g.: 

`github.com/mozz100/tohora/i*sues/6&arbitrarynumber=2`

is cut down to:

`github.com/mozz100/tohora/i*sues/6`

**Comment by mozz100** [comment]
Could you confirm the way you are encoding the URL?  You don't mention if you are using a language like python, or are you working in a bash script with curl?

e.g. if your URL is `http://example.com?q=hello&sort=desc` then it should be URL encoded as `http%3A%2F%2Fexample.com%3Fq%3Dhello%26sort%3Ddesc`.

Hopefully, encoding is the solution to this.  If not, please let me know and I'll fire the code up and try and reproduce.

**Comment by neutronium-alchemist** [comment]
It was via the Balena Dash environment variable, and later, through a node-red flow that I was trying to update the URL. Percent-encoding the ampersand fixes the issue.

Thank you
