### ISSUE TITLE
Slack integration issues

### ISSUE THREAD

**Issue by kamicrafted** [mozz100/screenserve#7]
Hello, I'm following the instructions on how to set up the Slack integration but having some trouble getting it to work.

The slash command is set up and installed on Slack, and the public URL is also working as expected (opening it in the browser it shows the Tohora UI). When I run the `/screen` command from Slack, it responds with the output of the HTML page's contents instead of updating the screen for some reason.

![image](https://user-images.githubusercontent.com/1197908/76478302-91e7d280-63de-11ea-9a79-a18831b5fbe5.png)

Any advice on addressing this issue would be much appreciated, thank you!

**Comment by mozz100** [comment]
Sorry to hear you are having issues.  Please check these things and if they don't work, share a screenshot of your Slack set up if you can.  

* Check that you are making a POST request to the `/launch/` endpoint (the trailing slash matters).
* Check that using the `curl` command from the `README.md` works - [this one](admin.site.register(Trophy))

**Comment by kamicrafted** [comment]
Thank you @mozz100, I'm not entirely sure where I should be making the POST request. Following the guide, I was able to get the public URL working (Tohora UI shows when accessing the URL) and my slack setup is as follows:

![image](https://user-images.githubusercontent.com/1197908/76813816-7e1de100-67cf-11ea-9f11-a393eb209e3b.png)

I wasn't sure if you meant to add /launch/ to the end of the public URL in Slack, which I've also tried without success. the curl command links to a "Not Found" page.

**Comment by mozz100** [comment]
Your Slack screenshot looks ok to me.  Sorry about the `curl` command, my bad: https://github.com/mozz100/tohora#using-from-scripts

So you would want to try:

```
curl --data-urlencode "url=https://www.google.com/?q=tohora&a=b" https://XXXXX.balena-devices.com/launch/
```

...and that should display a Google results page.

If things aren't working after that, please share the logs from your balena dash container (you can get them through balena's management pages) during a run of the `/screen` command, and I'll see if I can work it out

**Comment by mozz100** [comment]
@kamicrafted - checking in to see if you made any progress
